src/objects/EmojiData__c.object
<CustomObject>
    <fields>
        <fullName>AddedIn__c</fullName>
        <description>Emoji version in which this codepoint/sequence was added (previously Unicode version).</description>
        <inlineHelpText>Emoji version in which this codepoint/sequence was added (previously Unicode version).</inlineHelpText>
        <label>Added In</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category group names.</description>
        <inlineHelpText>Category group names.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undefined</fullName>
                    <default>true</default>
                    <label>Undefined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HasAppleImage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A flag for whether the given image set has an image (named by the image prop) available.</description>
        <inlineHelpText>A flag for whether the given image set has an image (named by the image prop) available.</inlineHelpText>
        <label>Has Apple Image</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HasFacebookImage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A flag for whether the given image set has an image (named by the image prop) available.</description>
        <inlineHelpText>A flag for whether the given image set has an image (named by the image prop) available.</inlineHelpText>
        <label>Has Facebook Image</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HasGoogleImage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A flag for whether the given image set has an image (named by the image prop) available.</description>
        <inlineHelpText>A flag for whether the given image set has an image (named by the image prop) available.</inlineHelpText>
        <label>Has Google Image</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HasTwitterImage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A flag for whether the given image set has an image (named by the image prop) available.</description>
        <inlineHelpText>A flag for whether the given image set has an image (named by the image prop) available.</inlineHelpText>
        <label>Has Twitter Image</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <description>The name of the image file.</description>
        <inlineHelpText>The name of the image file.</inlineHelpText>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NonQualified__c</fullName>
        <description>For emoji that also have usage without a variation selector, that version is included here (otherwise is null).</description>
        <inlineHelpText>For emoji that also have usage without a variation selector, that version is included here (otherwise is null).</inlineHelpText>
        <label>Non Qualified</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SheetX__c</fullName>
        <description>The position of the image in the spritesheets</description>
        <inlineHelpText>The position of the image in the spritesheets</inlineHelpText>
        <label>Sheet X</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SheetY__c</fullName>
        <description>The position of the image in the spritesheets</description>
        <inlineHelpText>The position of the image in the spritesheets</inlineHelpText>
        <label>Sheet Y</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShortNames__c</fullName>
        <description>An array of all the known short names.</description>
        <inlineHelpText>An array of all the known short names.</inlineHelpText>
        <label>Short Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <description>Global sorting index for all emoji, based on Unicode CLDR ordering.</description>
        <inlineHelpText>Global sorting index for all emoji, based on Unicode CLDR ordering.</inlineHelpText>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <description>Sub-category group names.</description>
        <inlineHelpText>Sub-category group names.</inlineHelpText>
        <label>Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undefined</fullName>
                    <default>true</default>
                    <label>Undefined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unified__c</fullName>
        <description>The Unicode codepoint, as 4-5 hex digits. Where an emoji needs 2 or more codepoints, they are specified like 1F1EA-1F1F8. For emoji that need to specifiy a variation selector (-FE0F), that is included here.</description>
        <inlineHelpText>The Unicode codepoint, as 4-5 hex digits. Where an emoji needs 2 or more codepoints, they are specified like 1F1EA-1F1F8. For emoji that need to specifiy a variation selector (-FE0F), that is included here.</inlineHelpText>
        <label>Unified</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>au__c</fullName>
        <description>The legacy Unicode codepoints used by various mobile vendors.</description>
        <inlineHelpText>The legacy Unicode codepoints used by various mobile vendors.</inlineHelpText>
        <label>au</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>docomo__c</fullName>
        <description>The legacy Unicode codepoints used by various mobile vendors.</description>
        <inlineHelpText>The legacy Unicode codepoints used by various mobile vendors.</inlineHelpText>
        <label>docomo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>google__c</fullName>
        <description>The legacy Unicode codepoints used by various mobile vendors.</description>
        <inlineHelpText>The legacy Unicode codepoints used by various mobile vendors.</inlineHelpText>
        <label>google</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>softbank__c</fullName>
        <description>The legacy Unicode codepoints used by various mobile vendors.</description>
        <inlineHelpText>The legacy Unicode codepoints used by various mobile vendors.</inlineHelpText>
        <label>softbank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Emoji Data</label>
    <nameField>
        <label>Emoji Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emojis Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Emoji.cls
public class Emoji  
{
	public String name;
	public String unified;
	public String non_qualified;
	public String docomo;
	public String au;
	public String softbank;
	public String google;
	public String image;
	public Integer sheet_x;
	public Integer sheet_y;
	public String short_name;
	public List<String> short_names;
	//public Object text;
	//public Object texts;
	public String category;
	public String subcategory;
	public Integer sort_order;
	public String added_in;
	public Boolean has_img_apple;
	public Boolean has_img_google;
	public Boolean has_img_twitter;
	public Boolean has_img_facebook;

	public static List<Emoji> parse(String json) 
	{
		return (List<Emoji>) System.JSON.deserialize(json, List<Emoji>.class);
	}

	public static String getEmojiJson()
	{
		StaticResource resource = [Select Id, Name,SystemModStamp
									From StaticResource
									Where Name = 'addeprop'
									Limit 1];
		return extractEmojiJson(resource);
	}

	private static String extractEmojiJson(StaticResource resource)
	{
		String results = '';
		String urlFile = '/resource/'
						+ String.valueOf(((DateTime)resource.get('SystemModStamp')).getTime())
						+ '/' 
						+ resource.get('Name')
						+ '/json/emoji.json';
		PageReference fileRef = new PageReference(urlFile);
		return fileRef.getContent().toString();
	}

	public static void doPost()
	{
		List<EmojiData__c> data = new List<EmojiData__c>();
		Map<String,EmojiData__c> existingData = getExistingEmojiData();
		for(Emoji em : Emoji.parse(Emoji.getEmojiJson()))
		{
			if(!existingData.containsKey(em.name))
			{
				data.add(prepareNewEmoji(em));

			}
		}
		if(!data.isEmpty())
		{
			Database.insert(data,false);
		}
	}

	public static Map<String,EmojiData__c> getExistingEmojiData()
	{
		Map<String,EmojiData__c> results = new Map<String,EmojiData__c>();
		for(List<EmojiData__c> recs : [Select Id, Name, Category__c,Subcategory__c
										From EmojiData__c 
										Order By SortOrder__c ASC])
		{
			if(!recs.isEmpty())
			{
				for(EmojiData__c ed : recs)
				{
					results.put(ed.Name,ed);
				}
			}
		}
		return results;
	}

	private static EmojiData__c prepareNewEmoji(Emoji em)
	{
		EmojiData__c ed = new EmojiData__c();
		ed.Name = em.name;
		ed.Unified__c = em.unified;
		ed.Category__c = em.category;
		ed.SubCategory__c = em.subcategory;
		ed.SortOrder__c = em.sort_order;
		ed.softbank__c = em.softbank;
		ed.ShortNames__c = em.short_name;
		ed.SheetY__c = em.sheet_y;
		ed.SheetX__c = em.sheet_x;
		ed.NonQualified__c = em.non_qualified;
		ed.Image__c = em.image;
		ed.HasTwitterImage__c = em.has_img_twitter;
		ed.HasGoogleImage__c = em.has_img_google;
		ed.HasFacebookImage__c = em.has_img_facebook;
		ed.HasAppleImage__c = em.has_img_apple;
		ed.Google__c = em.google;
		ed.docomo__c = em.docomo;
		ed.au__c = em.au;
		ed.AddedIn__c = em.added_in;
		return ed;
	}
}